"""
pointnet_classifier.py — PointNet Classifier for Point Clouds.

Trains and evaluates PointNet on spatial blocks of point clouds.
Requires train_data_blocks.npz generated by run_preprocessing.py.

WHY POINTNET?
Unlike our MLP which works on segment-level features,
PointNet processes raw point cloud blocks directly.
It learns spatial relationships between points that
segment-level features might miss.

Recommended: Run on GPU for best performance.
On CPU expect ~5-10 minutes per epoch.

Usage:
    python pointnet_classifier.py --city riga --epochs 50
    python pointnet_classifier.py --city warsaw --epochs 50 --batch 8
"""

import numpy as np
import os
import argparse
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import (classification_report, confusion_matrix,
                             balanced_accuracy_score, f1_score)

from pointnet import PointNetSeg
from utils import SEED

np.random.seed(SEED)
torch.manual_seed(SEED)


class PointCloudBlockDataset(Dataset):
    def __init__(self, blocks):
        self.blocks = blocks

    def __len__(self):
        return len(self.blocks)

    def __getitem__(self, idx):
        xyz, feat, labels = self.blocks[idx]

        # Normalize features per block
        feat = np.nan_to_num(feat, nan=0.0, posinf=0.0, neginf=0.0)
        feat_mean = feat.mean(axis=0, keepdims=True)
        feat_std  = feat.std(axis=0, keepdims=True) + 1e-6
        feat      = (feat - feat_mean) / feat_std

        return (torch.FloatTensor(xyz),
                torch.FloatTensor(feat),
                torch.LongTensor(labels))


def remap(y):
    """Remap IFP codes to 0/1/2: other=0, sidewalk=1, street=2"""
    y_new = np.zeros_like(y, dtype=np.int64)
    y_new[y == 2]  = 1
    y_new[y == 11] = 2
    return y_new


def load_blocks(city):
    """Load train_data_blocks.npz for a city."""
    path = f"preprocessed/{city}/train_data_blocks.npz"
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing {path}.\n"
            f"Run: python run_preprocessing.py datasets/{city}_subsampled.laz "
            f"-o preprocessed/{city} (WITHOUT --skip-blocks)")

    print(f"  Loading blocks from {path}...")
    data = np.load(path, allow_pickle=True)

    train_blocks = list(zip(data["train_xyz"],
                            data["train_features"],
                            data["train_labels"]))
    test_blocks  = list(zip(data["test_xyz"],
                            data["test_features"],
                            data["test_labels"]))
    num_features = train_blocks[0][1].shape[1]
    print(f"  {len(train_blocks)} train blocks, {len(test_blocks)} test blocks")
    print(f"  Features per point: {num_features}")
    return train_blocks, test_blocks, num_features


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--city",   required=True)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch",  type=int, default=4)
    parser.add_argument("--lr",     type=float, default=0.001)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n{'='*60}")
    print(f"PointNet Classifier — {args.city.upper()}")
    print(f"Device: {device}")
    print(f"{'='*60}")

    # ── Load data ──────────────────────────────────────────────────────────
    train_blocks, test_blocks, num_features = load_blocks(args.city)

    val_size     = max(1, int(len(train_blocks) * 0.1))
    val_blocks   = train_blocks[:val_size]
    train_blocks = train_blocks[val_size:]

    print(f"\nTrain: {len(train_blocks)} | Val: {len(val_blocks)} | "
          f"Test: {len(test_blocks)} blocks")

    train_loader = DataLoader(PointCloudBlockDataset(train_blocks),
                              batch_size=args.batch, shuffle=True,
                              drop_last=True)
    val_loader   = DataLoader(PointCloudBlockDataset(val_blocks),
                              batch_size=args.batch, shuffle=False)
    test_loader  = DataLoader(PointCloudBlockDataset(test_blocks),
                              batch_size=args.batch, shuffle=False)

    # ── Class weights ──────────────────────────────────────────────────────
    all_labels = remap(np.concatenate([b[2] for b in train_blocks]))
    classes, counts = np.unique(all_labels, return_counts=True)
    weights    = 1.0 / counts
    weights    = weights / weights.sum() * len(classes)
    weight_vec = np.ones(3, dtype=np.float32)
    for c, w in zip(classes, weights):
        if c < 3:
            weight_vec[c] = w
    class_weights = torch.FloatTensor(weight_vec).to(device)
    print(f"Class weights: {weight_vec.round(3)}")

    # ── Model ──────────────────────────────────────────────────────────────
    model     = PointNetSeg(d_in=num_features + 3, num_classes=3).to(device)
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.5)

    # ── Training ───────────────────────────────────────────────────────────
    best_val_acc = 0.0
    train_losses = []
    val_accs     = []

    print(f"\nTraining PointNet for {args.epochs} epochs...")
    for epoch in range(args.epochs):
        model.train()
        epoch_loss = 0

        for i, (xyz, feat, labels) in enumerate(train_loader):
            xyz, feat = xyz.to(device), feat.to(device)
            labels    = torch.LongTensor(remap(labels.numpy())).to(device)

            optimizer.zero_grad()
            out  = model(xyz, feat).transpose(1, 2)  # (B, C, N)
            loss = criterion(out, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        scheduler.step()
        epoch_loss /= len(train_loader)
        train_losses.append(epoch_loss)

        # Validation
        model.eval()
        all_preds, all_true = [], []
        with torch.no_grad():
            for xyz, feat, labels in val_loader:
                xyz, feat = xyz.to(device), feat.to(device)
                labels    = remap(labels.numpy())
                out       = model(xyz, feat)
                preds     = out.argmax(dim=-1).cpu().numpy()
                all_preds.extend(preds.flatten())
                all_true.extend(labels.flatten())

        val_acc = balanced_accuracy_score(all_true, all_preds)
        val_accs.append(val_acc)

        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1:3d}/{args.epochs} | "
                  f"Loss: {epoch_loss:.4f} | "
                  f"Val Balanced Acc: {val_acc*100:.1f}%")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            os.makedirs("models", exist_ok=True)
            torch.save(model.state_dict(),
                       f"models/{args.city}_pointnet.pt")

    print(f"\nBest validation accuracy: {best_val_acc*100:.1f}%")

    # ── Test evaluation ────────────────────────────────────────────────────
    model.load_state_dict(torch.load(f"models/{args.city}_pointnet.pt",
                                      map_location=device))
    model.eval()

    test_preds, test_true = [], []
    with torch.no_grad():
        for xyz, feat, labels in test_loader:
            xyz, feat = xyz.to(device), feat.to(device)
            labels    = remap(labels.numpy())
            out       = model(xyz, feat)
            preds     = out.argmax(dim=-1).cpu().numpy()
            test_preds.extend(preds.flatten())
            test_true.extend(labels.flatten())

    bal_acc = balanced_accuracy_score(test_true, test_preds)
    sw_f1   = f1_score(test_true, test_preds, labels=[1],
                       average=None, zero_division=0)[0]

    print(f"\nTest Results:")
    print(f"Balanced Accuracy: {bal_acc*100:.1f}%  |  Sidewalk F1: {sw_f1:.3f}")
    print(classification_report(test_true, test_preds,
                                 target_names=["other", "sidewalk", "street"],
                                 zero_division=0))

    # ── Training curves ────────────────────────────────────────────────────
    os.makedirs("results", exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].plot(train_losses, color="#1565C0")
    axes[0].set_title("Training Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")

    axes[1].plot([v * 100 for v in val_accs], color="#2E7D32")
    axes[1].set_title("Validation Balanced Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Balanced Accuracy (%)")

    plt.suptitle(f"PointNet Training — {args.city.upper()}", fontsize=13)
    plt.tight_layout()
    plt.savefig(f"results/{args.city}_pointnet_training.png", dpi=150)
    plt.show()

    # ── Confusion matrix ───────────────────────────────────────────────────
    cm      = confusion_matrix(test_true, test_preds, labels=[0, 1, 2])
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    plt.figure(figsize=(7, 5))
    sns.heatmap(cm_norm, annot=True, fmt=".2%", cmap="Blues",
                xticklabels=["other", "sidewalk", "street"],
                yticklabels=["other", "sidewalk", "street"])
    plt.title(f"PointNet Confusion Matrix — {args.city.upper()}")
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig(f"results/{args.city}_pointnet_confusion.png", dpi=150)
    plt.show()

    print(f"\n✅ Model saved → models/{args.city}_pointnet.pt")
